package install

import (
	"bytes"
	"context"
	"encoding/xml"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"time"
)

const Label = "com.magichop.agent"

type Paths struct {
	ConfigPath string
	PlistPath  string
}

func DefaultPaths() (Paths, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return Paths{}, fmt.Errorf("find home directory: %w", err)
	}
	return Paths{
		ConfigPath: filepath.Join(home, ".config", "magichop", "config.json"),
		PlistPath:  filepath.Join(home, "Library", "LaunchAgents", Label+".plist"),
	}, nil
}

func Mac(binary string, paths Paths) error {
	if runtime.GOOS != "darwin" {
		return fmt.Errorf("mac install requires macOS")
	}
	if _, err := exec.LookPath("brew"); err != nil {
		return fmt.Errorf("homebrew is required: %w", err)
	}
	if _, err := exec.LookPath("blueutil"); err != nil {
		cmdCtx, cancel := context.WithTimeout(context.Background(), 5*time.Minute)
		defer cancel()
		cmd := exec.CommandContext(cmdCtx, "brew", "install", "blueutil")
		if out, runErr := cmd.CombinedOutput(); runErr != nil {
			return fmt.Errorf("install blueutil: %w: %s", runErr, strings.TrimSpace(string(out)))
		}
	}
	for _, dir := range []string{filepath.Dir(paths.ConfigPath), filepath.Dir(paths.PlistPath)} {
		if err := os.MkdirAll(dir, 0o700); err != nil {
			return fmt.Errorf("create directory %s: %w", dir, err)
		}
	}
	plist, err := GenerateLaunchAgentPlist(binary, paths.ConfigPath)
	if err != nil {
		return err
	}
	if err := os.WriteFile(paths.PlistPath, plist, 0o600); err != nil {
		return fmt.Errorf("write launchagent plist: %w", err)
	}
	uid := fmt.Sprintf("%d", os.Getuid())
	runLaunchctl("bootout", "gui/"+uid, paths.PlistPath)
	if out, err := runLaunchctlOutput("bootstrap", "gui/"+uid, paths.PlistPath); err != nil {
		return fmt.Errorf("bootstrap launchagent: %w: %s", err, strings.TrimSpace(string(out)))
	}
	runLaunchctl("enable", "gui/"+uid+"/"+Label)
	runLaunchctl("kickstart", "-k", "gui/"+uid+"/"+Label)
	return nil
}

func UninstallMac(paths Paths, purgeConfig bool) error {
	if runtime.GOOS != "darwin" {
		return fmt.Errorf("mac uninstall requires macOS")
	}
	uid := fmt.Sprintf("%d", os.Getuid())
	runLaunchctl("bootout", "gui/"+uid, paths.PlistPath)
	if err := os.Remove(paths.PlistPath); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("remove %s: %w", paths.PlistPath, err)
	}
	if purgeConfig {
		if err := os.Remove(paths.ConfigPath); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("remove config: %w", err)
		}
	}
	return nil
}

func GenerateLaunchAgentPlist(binary, configPath string) ([]byte, error) {
	if binary == "" {
		return nil, fmt.Errorf("binary path is required")
	}
	var b bytes.Buffer
	b.WriteString(xml.Header)
	b.WriteString(`<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">` + "\n")
	b.WriteString(`<plist version="1.0"><dict>`)
	writeKeyString(&b, "Label", Label)
	writeKeyArray(&b, "ProgramArguments", []string{binary, "daemon"})
	b.WriteString(`<key>EnvironmentVariables</key><dict>`)
	writeKeyString(&b, "MAGICHOP_CONFIG", configPath)
	writeKeyString(&b, "PATH", "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin")
	b.WriteString(`</dict>`)
	writeKeyBool(&b, "RunAtLoad", true)
	writeKeyBool(&b, "KeepAlive", true)
	b.WriteString(`</dict></plist>`)
	b.WriteByte('\n')
	return b.Bytes(), nil
}

func GenerateRaycastScript(binary string) ([]byte, error) {
	if binary == "" {
		return nil, fmt.Errorf("binary path is required")
	}
	var b bytes.Buffer
	b.WriteString("#!/bin/bash\n\n")
	b.WriteString("# Raycast Script Command\n")
	b.WriteString("#\n")
	b.WriteString("# Generated by MagicHop. Add this file through Raycast Settings -> Extensions -> Script Commands.\n")
	b.WriteString("#\n")
	b.WriteString("# Required parameters:\n")
	b.WriteString("# @raycast.schemaVersion 1\n")
	b.WriteString("# @raycast.title Claim Bluetooth Device\n")
	b.WriteString("# @raycast.mode compact\n")
	b.WriteString("# @raycast.packageName MagicHop\n\n")
	b.WriteString("# Optional parameters:\n")
	b.WriteString("# @raycast.icon 🖱️\n")
	b.WriteString("# @raycast.currentDirectoryPath ~\n")
	b.WriteString("# @raycast.needsConfirmation false\n\n")
	b.WriteString("# Documentation:\n")
	b.WriteString("# @raycast.description Claim the default configured Bluetooth device through MagicHop.\n\n")
	b.WriteString("set -euo pipefail\n")
	b.WriteString("exec ")
	b.WriteString(shellQuote(binary))
	b.WriteString(" claim\n")
	return b.Bytes(), nil
}

func WriteRaycastScript(dir, binary string) (string, error) {
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return "", fmt.Errorf("create raycast dir: %w", err)
	}
	script, err := GenerateRaycastScript(binary)
	if err != nil {
		return "", err
	}
	path := filepath.Join(dir, "magichop-claim.sh")
	if err := os.WriteFile(path, script, 0o755); err != nil { //nolint:gosec // Raycast scripts must be executable
		return "", fmt.Errorf("write raycast script: %w", err)
	}
	return path, nil
}

func writeKeyString(b *bytes.Buffer, key, value string) {
	b.WriteString(`<key>`)
	xml.EscapeText(b, []byte(key)) //nolint:errcheck // bytes.Buffer writes cannot fail
	b.WriteString(`</key><string>`)
	xml.EscapeText(b, []byte(value)) //nolint:errcheck // bytes.Buffer writes cannot fail
	b.WriteString(`</string>`)
}

func writeKeyArray(b *bytes.Buffer, key string, values []string) {
	b.WriteString(`<key>`)
	xml.EscapeText(b, []byte(key)) //nolint:errcheck // bytes.Buffer writes cannot fail
	b.WriteString(`</key><array>`)
	for _, value := range values {
		b.WriteString(`<string>`)
		xml.EscapeText(b, []byte(value)) //nolint:errcheck // bytes.Buffer writes cannot fail
		b.WriteString(`</string>`)
	}
	b.WriteString(`</array>`)
}

func writeKeyBool(b *bytes.Buffer, key string, value bool) {
	b.WriteString(`<key>`)
	xml.EscapeText(b, []byte(key)) //nolint:errcheck // bytes.Buffer writes cannot fail
	if value {
		b.WriteString(`</key><true/>`)
		return
	}
	b.WriteString(`</key><false/>`)
}

func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", `'\''`) + "'"
}

func runLaunchctl(args ...string) {
	_, _ = runLaunchctlOutput(args...)
}

func runLaunchctlOutput(args ...string) ([]byte, error) {
	cmdCtx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()
	cmd := exec.CommandContext(cmdCtx, "launchctl", args...)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return out, fmt.Errorf("run launchctl: %w", err)
	}
	return out, nil
}
